export const managers = {
    1: { name: "Dom" },
    2: { name: "Martin" },
    3: { name: "Si" },
    4: { name: "John" },
    5: { name: "Tim" },
    6: { name: "Nathan" },
    7: { name: "Charlie" },
    8: { name: "KY" },
    9: { name: "Eric" },
    10: { name: "Maz" },
    11: { name: "Devon"},
    12: { name: "Dobbie"},
    13: { name: "Steve"},
};