export const teams = {
    1: { name: "Atlanta Hawks", image: "hawks.svg" },
    2: { name: "Boston Celtics", image: "celtics.svg" },
    3: { name: "Brooklyn Nets", image: "nets.svg" },
    4: { name: "Charlotte Hornets", image: "hornets.svg" },
    5: { name: "Chicago Bulls", image: "bulls.svg" },
    6: { name: "Cleveland Cavaliers", image: "cavaliers.svg" },
    7: { name: "Dallas Mavericks", image: "mavericks.svg" },
    8: { name: "Denver Nuggets", image: "nuggets.svg" },
    9: { name: "Detroit Pistons", image: "pistons.svg" },
    10: { name: "Golden State Warriors", image: "warriors.svg" },
    11: { name: "Houston Rockets", image: "rockets.svg" },
    12: { name: "Indiana Pacers", image: "pacers.svg" },
    13: { name: "Los Angeles Clippers", image: "clippers.svg" },
    14: { name: "Los Angeles Lakers", image: "lakers.svg" },
    15: { name: "Memphis Grizzlies", image: "grizzlies.svg" },
    16: { name: "Miami Heat", image: "heat.svg" },
    17: { name: "Milwaukee Bucks", image: "bucks.svg" },
    18: { name: "Minnesota Timberwolves", image: "timberwolves.svg" },
    19: { name: "New Orleans Pelicans", image: "pelicans.svg" },
    20: { name: "New York Knicks", image: "knicks.svg" },
    21: { name: "Oklahoma City Thunder", image: "thunder.svg" },
    22: { name: "Orlando Magic", image: "magic.svg" },
    23: { name: "Philadelphia 76ers", image: "76ers.svg" },
    24: { name: "Phoenix Suns", image: "suns.svg" },
    25: { name: "Portland Trail Blazers", image: "blazers.svg" },
    26: { name: "Sacramento Kings", image: "kings.svg" },
    27: { name: "San Antonio Spurs", image: "spurs.svg" },
    28: { name: "Toronto Raptors", image: "raptors.svg" },
    29: { name: "Utah Jazz", image: "jazz.svg" },
    30: { name: "Washington Wizards", image: "wizards.svg" }
};
