export const teams = {
    1: { name: "Atlanta Hawks", image: null },
    2: { name: "Boston Celtics", image: null },
    3: { name: "Brooklyn Nets", image: null },
    4: { name: "Charlotte Hornets", image: null },
    5: { name: "Chicago Bulls", image: null },
    6: { name: "Cleveland Cavaliers", image: null },
    7: { name: "Dallas Mavericks", image: null },
    8: { name: "Denver Nuggets", image: null },
    9: { name: "Detroit Pistons", image: null },
    10: { name: "Golden State Warriors", image: null },
    11: { name: "Houston Rockets", image: null },
    12: { name: "Indiana Pacers", image: null },
    13: { name: "Los Angeles Clippers", image: null },
    14: { name: "Los Angeles Lakers", image: null },
    15: { name: "Memphis Grizzlies", image: null },
    16: { name: "Miami Heat", image: null },
    17: { name: "Milwaukee Bucks", image: null },
    18: { name: "Minnesota Timberwolves", image: null },
    19: { name: "New Orleans Pelicans", image: null },
    20: { name: "New York Knicks", image: null },
    21: { name: "Oklahoma City Thunder", image: null },
    22: { name: "Orlando Magic", image: null },
    23: { name: "Philadelphia 76ers", image: null },
    24: { name: "Phoenix Suns", image: null },
    25: { name: "Portland Trail Blazers", image: null },
    26: { name: "Sacramento Kings", image: null },
    27: { name: "San Antonio Spurs", image: null },
    28: { name: "Toronto Raptors", image: null },
    29: { name: "Utah Jazz", image: null },
    30: { name: "Washington Wizards", image: null }
};
